version: "3.8"

services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - POSTGRES_DB:/var/lib/postgresql/data
    env_file:
      - .env
    # environment:
    #   - POSTGRES_DB=${POSTGRES_DB}
    #   - POSTGRES_USER=${POSTGRES_USER}
    #   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # - PGDATA=/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    
  api:
    image: docker.infogerance.d-fi.fr/${APP_NAME_BACKEND}:${APP_VERSION}
    depends_on:
      - db
    ports:
      - ${BACKEND_PORT:-8080}:8080
    env_file:
      - .env

volumes:
  POSTGRES_DB: