version: "3.8"

services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - POSTGRES_DB:/var/lib/postgresql/data
    env_file:
      - dev.env
    # environment:
    #   - POSTGRES_DB=${POSTGRES_DB}
    #   - POSTGRES_USER=${POSTGRES_USER}
    #   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # - PGDATA=/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432

  api:
    image: python:${PYTHON_VERSION}
    depends_on:
      - db
    ports:
      - ${BACKEND_PORT:-5000}:5000
    volumes:
      - ./be:/app
    command: >
      bash -c "pip install virtualenv && virtualenv env && source env/bin/activate && pip install -r requirements.txt && cd src && python main.py"
    env_file:
      - dev.env
    working_dir: /app
    stdin_open: true
    tty: true

volumes:
  POSTGRES_DB: